### ISSUE TITLE
Getting "Nothing is Submitted" error

### ISSUE THREAD

**Issue by johndesp** [daniely/lita-jenkins#12]
Hi. 
I can list my jobs with "Lita jenkins list".
I get back my job numbers.

When I run "Lita jenkins build 2"

I get back:

Nothing is submitted</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/> 

My jenkins job requires one paramter. However, I have a default value set.

What do you think is wrong?

thanks

John

**Comment by miketheman** [comment]
@johndesp Thanks for bringing this up - this is likely part of how Jenkins parses a build request when dealing with parameters.
This has been previously been reported with a hubot jenkins plugin, and the handling there was to resubmit the job with a new path that allows for an empty param.

I'm going to be looking at adding parameterized builds to the plugin soon, and will make sure to test a default value.
