### ISSUE TITLE
Jobs added after Lita startup are not found with `list` command

### ISSUE THREAD

**Issue by miketheman** [daniely/lita-jenkins#17]
Filing this so I don't forget.

If Lita has started up, and Jenkins jobs are added to the server, these will not appear in a `jenkins list` command, as we store the job definitions as a class attribute, and since it exists, we do not query the server again.

Unsure of the best way to handle this. I can conceive of storing a "last_update" timestamp in redis or class attribute, and TTL to expire the job list (default: once a day?).
Another might be to add a `jenkins list refresh` command that forces a reload of jobs.

Simple workaround is to restart Lita.

**Comment by daniely** [comment]
Looks like `jobs` was memoized for performance...so the api wouldn't be hit too often. Adding a `jenkins list refresh` sounds good. Or what if we just remove memoizing and keep hitting the api when we need to?

**Comment by miketheman** [comment]
I think removing the memoization might actually be the best solution, as I don't think these calls are "heavy", or even frequent enough to realistically need the performance boost.

I'm :+1: for removal, if you're on board.

**Comment by daniely** [comment]
Sound good.
