### ISSUE TITLE
http.get fails for 301 (redirects) and/or https url with self-signed certificates

### ISSUE THREAD

**Issue by dtogias** [daniely/lita-jenkins#2]
Not sure if this can be fixed in the jenkins plugin, but i open a lita issue as well.

**Comment by miketheman** [comment]
[Linked issue](https://github.com/jimmycuadra/lita/issues/75), they closed as they beleive it should be a handler option, not a global one.

**Comment by miketheman** [comment]
This was solved in #29, will close when plugin released.

**Comment by miketheman** [comment]
The fix for this was released in 0.0.5 https://rubygems.org/gems/lita-jenkins/versions/0.0.5
