### ISSUE TITLE
Instruction to build job with parameters

### ISSUE THREAD

**Issue by akhy** [daniely/lita-jenkins#32]
It seems the current version can already build jobs with parameters, but I cannot find the instruction to do that.

Does the regex in this code already support parameters? What is the example command to build with parameters?

``` ruby
route /j(?:enkins)? b(?:uild)? ([\w\.\-_ ]+)(, (.+))?/i, :jenkins_build, command: true, help: {
    'jenkins b(uild) <job_id or job_name>' => 'builds the job specified by ID or name. List jobs to get ID.'
}
```

**Comment by miketheman** [comment]
@akhy I guess the `help` doesn't display it very well.

You can see examples in the specs:
https://github.com/daniely/lita-jenkins/blob/master/spec/lita/handlers/jenkins_spec.rb#L9
https://github.com/daniely/lita-jenkins/blob/master/spec/lita/handlers/jenkins_spec.rb#L151-L166
