### ISSUE TITLE
Using job names in addition to existing IDs

### ISSUE THREAD

**Issue by miketheman** [daniely/lita-jenkins#4]
We've been using [hubot's jenkins integration](https://github.com/github/hubot-scripts/blob/master/src/scripts/jenkins.coffee) for a while, and are looking to port over to lita - I've been making some good progress on contributing to other plugins like lita-alias, and wrote my own (https://github.com/miketheman/lita-goforit).

In our current deploy, we use the jenkins syntax like this: 
```
hubot jenkins build prod-jenkins-job
hubot jenkins build prod-jenkins-job, PARAM_NAME=SOMEBUILDPARAM
```

I'm asking if there's interest in having this plugin be extended to support this approach, as I'm happy to dig in to make it happen, instead of starting a whole other plugin.

**Comment by daniely** [comment]
> I'm asking if there's interest in having this plugin be extended to support this approach, as I'm happy to dig in to make it happen, instead of starting a whole other plugin.

If it seems useful to you then sure!

I haven't used lita-jenkins for awhile now so I'm honestly not the best person to decide.

**Comment by miketheman** [comment]
> I haven't used lita-jenkins for awhile now so I'm honestly not the best person to decide.

Have you gone to something else? Would you consider co-collaborator/ownership?
