### ISSUE TITLE
Support "describe" action

### ISSUE THREAD

**Issue by scarytom** [daniely/lita-jenkins#8]
The hubot-jenkins plugin (https://github.com/github/hubot-scripts/blob/master/src/scripts/jenkins.coffee) supports "list", "build", and "describe" actions. Please could lita-jenkins be enhanced to support the describe action?

**Comment by daniely** [comment]
I don't have time to actively work on this right now but pull requests are welcome.

**Comment by scarytom** [comment]
No problem. I might actually get around to working on this -- if I do, will you have time to do a release of the new rubygem?

**Comment by daniely** [comment]
Yes of course.

I haven't completely abandoned this project or anything. It's just hard to work on because of 1) time constraints 2) I don't currently actively use it.

But @miketheman has been contributing lately so I think I'll invite him to the project to help out.

**Comment by miketheman** [comment]
Thanks for the invite. The `describe` functionality looks interesting - @scarytom if you take a pass at it, I'd like to help.

I think I might focus a bit more on the `build` interface - as I want to add the ability to pass build params, as well as throw some heavier testing at the whole thing.
