### ISSUE TITLE
tag v0.0.3 release

### ISSUE THREAD

**Issue by scarytom** [daniely/lita-jenkins#9]
The Lita plugins page (https://www.lita.io/plugins) reports that v0.0.3 is the latest version of lita-jenkins, and this is available from https://rubygems.org/gems/lita-jenkins but there is no tag for v0.0.3 in the git repo.  Please add a tag for v0.0.3 -- I think the revision should be 97d4c11659d32fd9531de005d5e2b319bba8cb8f

`git tag -a v0.0.3 97d4c11659d32fd9531de005d5e2b319bba8cb8f -m "Version 0.0.3"`

**Comment by scarytom** [comment]
Sadly, I cannot do this as a pull request

**Comment by daniely** [comment]
@scarytom I think there's some confusion. I was talking about doing a PR for [issue 8](https://github.com/daniely/lita-jenkins/issues/8)

**Comment by scarytom** [comment]
No confusion, I was just predicting you closing this issue with the same reasoning as issue 8, so was pre-empting with a comment.

**Comment by daniely** [comment]
Ah ok. Well, you gave me exactly all the info I needed so the tagging has been done. 

Thank you @scarytom for the help.
